# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "FAQs"
  pageRef = "FAQs"
  weight = 20

[[main]]
  name = "Reviews"
  pageRef = "Reviews"
  weight = 30

[[main]]
  name = "Kids Electric Cars"
  pageRef = "kids-electric-cars"
  weight = 40
  
[[main]]
  name = "Mercedes Kids Electric Car"
  pageRef = "mercedes-kids-electric-car"
  weight = 45
  parent = "Kids Electric Cars"

[[main]]
  name = "Affiliate Disclosure"
  pageRef = "affiliate-disclosure"
  weight = 50
  
[[main]]
  name = "Privacy Policy"
  pageRef = "privacy-policy"
  weight = 60
  
[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 70  


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10
